language: node_js
node_js:
  - "12"
  - "10"

env:
  - GRAPHQL_VERSION='legacy'
  - GRAPHQL_VERSION='latest'

install:
  - npm config set spin=false
  - npm install

script:
  - if [[ $GRAPHQL_VERSION == "latest" ]]; then
      npm run lint;
    fi
  - if [[ $GRAPHQL_VERSION == "latest" ]]; then
      npm run format:check;
    fi
  - npm run compile
  - if [[ $GRAPHQL_VERSION == "legacy" ]]; then
      npm install graphql@0.13.0;
    fi
  - npm run test

# Allow Travis tests to run in containers.
sudo: false
