language: node_js
node_js:
  - "13"
  - "12"
  - "10"

env:
  - GRAPHQL_VERSION='0.12'
  - GRAPHQL_VERSION='0.13'
  - GRAPHQL_VERSION='14.0'
  - GRAPHQL_VERSION='14.1'
  - GRAPHQL_VERSION='14.2'
  - GRAPHQL_VERSION='14.3'
  - GRAPHQL_VERSION='14.4'
  - GRAPHQL_VERSION='14.5'
  - GRAPHQL_VERSION='14.6'
  - GRAPHQL_VERSION='rc'

install:
  - npm config set spin=false
  - npm install

script:
  - node_version=$(node -v); if [[ ${node_version:1:2} == "13" && $GRAPHQL_VERSION == "14.6" ]]; then
      npm run lint;
    fi
  - node_version=$(node -v); if [[ ${node_version:1:2} == "13" && $GRAPHQL_VERSION == "14.6" ]]; then
      npm run format:check;
    fi
  - npm run compile
  - npm install graphql@$GRAPHQL_VERSION
  - npm run test

# Allow Travis tests to run in containers.
sudo: false
