# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: GraphQL Tools
propertytitle: Using GraphQL Tools
subtitle: GraphQL Tools Guide
description: A guide to using GraphQL Tools.
versions:
  - '1'
sidebar_categories:
  null:
    - index
    - generate-schema
    - resolvers
    - scalars
    - mocking
    - connectors
    - remote-schemas
    - schema-directives
    - schema-stitching
  Related:
    - title: Apollo Server
      href: https://www.apollographql.com/docs/apollo-server/
    - title: GraphQL Subscriptions
      href: https://www.apollographql.com/docs/graphql-subscriptions/
github_repo: apollographql/graphql-tools
content_root: docs/source

typescript_api_box:
  data_file: docs.json

apis:
  docsearch:
    apiKey: 768e823959d35bbd51e4b2439be13fb7
    indexName: apollodata

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.apollographql.com/docs/graphql-tools/
root: /docs/graphql-tools/

public_dir: public/docs/graphql-tools